import fs from 'fs-extra';
import path from 'node:path';
import type {
  ScaffoldContext,
  FeatureManifest,
  FeatureDependencies,
  ComposedDeps,
} from '../types.js';

/**
 * Loads and parses a feature's feature.json manifest.
 * Throws if the file is missing or malformed.
 */
export async function loadManifest(featureDir: string): Promise<FeatureManifest> {
  const manifestPath = path.join(featureDir, 'feature.json');
  const raw = await fs.readJson(manifestPath) as FeatureManifest;
  return raw;
}

/**
 * Merges prod and dev dependency lists from all feature manifests.
 * Only includes deps that apply to the current context (UI library + language).
 * Deduplicates automatically.
 */
export function mergeManifests(
  manifests: FeatureManifest[],
  ctx: ScaffoldContext,
): ComposedDeps {
  const prod = new Set<string>();
  const dev = new Set<string>();

  for (const manifest of manifests) {
    collectDeps(manifest.dependencies, ctx, prod);
    if (manifest.devDependencies) {
      collectDeps(manifest.devDependencies, ctx, dev);
    }
  }

  return { prod: [...prod], dev: [...dev] };
}

function collectDeps(
  deps: FeatureDependencies,
  ctx: ScaffoldContext,
  target: Set<string>,
): void {
  for (const pkg of deps.any ?? []) target.add(pkg);

  const uiDeps = ctx.ui === 'shadcn' ? (deps.shadcn ?? []) : (deps.heroui ?? []);
  for (const pkg of uiDeps) target.add(pkg);

  const langDeps = ctx.isTS ? (deps.ts ?? []) : (deps.js ?? []);
  for (const pkg of langDeps) target.add(pkg);
}

/**
 * Emits src/router/routes.generated.[ext] in the target project directory.
 * Aggregates routes and navItems from all feature manifests.
 *
 * The generated file is a plain JS/TS module exporting two const arrays:
 *   - routes   – used by the router layer to build the route tree
 *   - navItems – used by layout components to render navigation
 */
export async function emitRoutes(
  manifests: FeatureManifest[],
  ctx: ScaffoldContext,
): Promise<void> {
  const routes = manifests.flatMap((m) => m.routes);
  const navItems = manifests.flatMap((m) => m.navItems);

  const outPath = path.join(
    ctx.targetDir,
    'src',
    'routes',
    `routes.generated.${ctx.ext}`,
  );

  const lines = [
    '// Auto-generated by create-my-react-boilerplate — do not edit manually.',
    '',
    `export const routes = ${JSON.stringify(routes, null, 2)};`,
    '',
    `export const navItems = ${JSON.stringify(navItems, null, 2)};`,
    '',
  ];

  await fs.outputFile(outPath, lines.join('\n'));
}
